# Generated by Django 3.1.7 on 2021-04-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StdentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='学号')),
                ('student_age', models.IntegerField(verbose_name='年龄')),
                ('student_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('student_sex', models.CharField(max_length=5, verbose_name='性别')),
                ('start_year', models.CharField(max_length=10, verbose_name='入学年份')),
                ('specialty', models.CharField(max_length=20, verbose_name='所在专业')),
                ('student_class', models.CharField(max_length=10, verbose_name='班级')),
                ('teacher_name', models.CharField(max_length=20, verbose_name='导员姓名')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=10, verbose_name='课程名')),
                ('sub_tcacher', models.CharField(max_length=10, verbose_name='课程老师')),
                ('sub_class', models.CharField(max_length=10, verbose_name='上课教师')),
            ],
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_ject', models.CharField(max_length=10, verbose_name='科目')),
                ('score', models.CharField(max_length=10, verbose_name='成绩')),
            ],
        ),
    ]
